"""Creacion inicial de toda la base de datos

Revision ID: 4aa970dc2c24
Revises: 
Create Date: 2025-07-14 19:48:42.532476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4aa970dc2c24'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('audit_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('table_name', sa.Text(), nullable=False),
    sa.Column('operation', sa.Text(), nullable=False),
    sa.Column('old_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('username', sa.Text(), nullable=True),
    sa.Column('app_user_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'audit_timestamp', name=op.f('pk_audit_log')),
    schema='control_equipos'
    )
    op.create_table('backup_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('backup_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('backup_status', sa.Text(), nullable=True),
    sa.Column('backup_type', sa.Text(), nullable=True),
    sa.Column('duration', sa.Interval(), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_backup_logs')),
    schema='control_equipos'
    )
    op.create_table('estados_equipo',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('permite_movimientos', sa.Boolean(), nullable=False),
    sa.Column('requiere_autorizacion', sa.Boolean(), nullable=False),
    sa.Column('es_estado_final', sa.Boolean(), nullable=False),
    sa.Column('color_hex', sa.String(length=7), nullable=True),
    sa.Column('icono', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_estados_equipo')),
    schema='control_equipos'
    )
    op.create_index(op.f('ix_control_equipos_estados_equipo_nombre'), 'estados_equipo', ['nombre'], unique=True, schema='control_equipos')
    op.create_table('permisos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permisos')),
    schema='control_equipos'
    )
    op.create_index(op.f('ix_control_equipos_permisos_nombre'), 'permisos', ['nombre'], unique=True, schema='control_equipos')
    op.create_table('proveedores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('contacto', sa.Text(), nullable=True),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('sitio_web', sa.String(length=255), nullable=True),
    sa.Column('rnc', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_proveedores')),
    schema='control_equipos'
    )
    op.create_index(op.f('ix_control_equipos_proveedores_nombre'), 'proveedores', ['nombre'], unique=True, schema='control_equipos')
    op.create_index(op.f('ix_control_equipos_proveedores_rnc'), 'proveedores', ['rnc'], unique=True, schema='control_equipos')
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    schema='control_equipos'
    )
    op.create_index(op.f('ix_control_equipos_roles_nombre'), 'roles', ['nombre'], unique=True, schema='control_equipos')
    op.create_table('software_catalogo',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('fabricante', sa.String(length=100), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('tipo_licencia', sa.String(length=50), nullable=False),
    sa.Column('metrica_licenciamiento', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_software_catalogo')),
    sa.UniqueConstraint('nombre', 'version', name='uq_software_nombre_version'),
    schema='control_equipos'
    )
    op.create_index(op.f('ix_control_equipos_software_catalogo_categoria'), 'software_catalogo', ['categoria'], unique=False, schema='control_equipos')
    op.create_index(op.f('ix_control_equipos_software_catalogo_fabricante'), 'software_catalogo', ['fabricante'], unique=False, schema='control_equipos')
    op.create_index(op.f('ix_control_equipos_software_catalogo_nombre'), 'software_catalogo', ['nombre'], unique=False, schema='control_equipos')
    op.create_table('tipos_documento',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('requiere_verificacion', sa.Boolean(), nullable=False),
    sa.Column('formato_permitido', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tipos_documento')),
    schema='control_equipos'
    )
    op.create_index(op.f('ix_control_equipos_tipos_documento_nombre'), 'tipos_documento', ['nombre'], unique=True, schema='control_equipos')
    op.create_table('tipos_mantenimiento',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('periodicidad_dias', sa.Integer(), nullable=True),
    sa.Column('requiere_documentacion', sa.Boolean(), nullable=False),
    sa.Column('es_preventivo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tipos_mantenimiento')),
    schema='control_equipos'
    )
    op.create_index(op.f('ix_control_equipos_tipos_mantenimiento_nombre'), 'tipos_mantenimiento', ['nombre'], unique=True, schema='control_equipos')
    op.create_table('equipos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('numero_serie', sa.String(length=100), nullable=False),
    sa.Column('codigo_interno', sa.String(length=100), nullable=True),
    sa.Column('estado_id', sa.UUID(), nullable=False),
    sa.Column('ubicacion_actual', sa.Text(), nullable=True),
    sa.Column('marca', sa.String(length=100), nullable=True),
    sa.Column('modelo', sa.String(length=100), nullable=True),
    sa.Column('fecha_adquisicion', sa.Date(), nullable=True),
    sa.Column('fecha_puesta_marcha', sa.Date(), nullable=True),
    sa.Column('fecha_garantia_expiracion', sa.Date(), nullable=True),
    sa.Column('valor_adquisicion', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('proveedor_id', sa.UUID(), nullable=True),
    sa.Column('centro_costo', sa.String(length=100), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('texto_busqueda', postgresql.TSVECTOR(), nullable=True),
    sa.ForeignKeyConstraint(['estado_id'], ['control_equipos.estados_equipo.id'], name=op.f('fk_equipos_estado_id_estados_equipo')),
    sa.ForeignKeyConstraint(['proveedor_id'], ['control_equipos.proveedores.id'], name=op.f('fk_equipos_proveedor_id_proveedores'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_equipos')),
    schema='control_equipos'
    )
    op.create_index(op.f('ix_control_equipos_equipos_centro_costo'), 'equipos', ['centro_costo'], unique=False, schema='control_equipos')
    op.create_index(op.f('ix_control_equipos_equipos_codigo_interno'), 'equipos', ['codigo_interno'], unique=True, schema='control_equipos')
    op.create_index(op.f('ix_control_equipos_equipos_estado_id'), 'equipos', ['estado_id'], unique=False, schema='control_equipos')
    op.create_index(op.f('ix_control_equipos_equipos_marca'), 'equipos', ['marca'], unique=False, schema='control_equipos')
    op.create_index(op.f('ix_control_equipos_equipos_modelo'), 'equipos', ['modelo'], unique=False, schema='control_equipos')
    op.create_index(op.f('ix_control_equipos_equipos_nombre'), 'equipos', ['nombre'], unique=False, schema='control_equipos')
    op.create_index(op.f('ix_control_equipos_equipos_numero_serie'), 'equipos', ['numero_serie'], unique=True, schema='control_equipos')
    op.create_index(op.f('ix_control_equipos_equipos_proveedor_id'), 'equipos', ['proveedor_id'], unique=False, schema='control_equipos')
    op.create_table('licencias_software',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('software_catalogo_id', sa.UUID(), nullable=False),
    sa.Column('clave_producto', sa.Text(), nullable=True),
    sa.Column('fecha_adquisicion', sa.Date(), nullable=False),
    sa.Column('fecha_expiracion', sa.Date(), nullable=True),
    sa.Column('proveedor_id', sa.UUID(), nullable=True),
    sa.Column('costo_adquisicion', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('numero_orden_compra', sa.String(length=100), nullable=True),
    sa.Column('cantidad_total', sa.Integer(), nullable=False),
    sa.Column('cantidad_disponible', sa.Integer(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['proveedor_id'], ['control_equipos.proveedores.id'], name=op.f('fk_licencias_software_proveedor_id_proveedores'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['software_catalogo_id'], ['control_equipos.software_catalogo.id'], name=op.f('fk_licencias_software_software_catalogo_id_software_catalogo'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_licencias_software')),
    schema='control_equipos'
    )
    op.create_index(op.f('ix_control_equipos_licencias_software_clave_producto'), 'licencias_software', ['clave_producto'], unique=False, schema='control_equipos')
    op.create_index(op.f('ix_control_equipos_licencias_software_fecha_expiracion'), 'licencias_software', ['fecha_expiracion'], unique=False, schema='control_equipos')
    op.create_index(op.f('ix_control_equipos_licencias_software_proveedor_id'), 'licencias_software', ['proveedor_id'], unique=False, schema='control_equipos')
    op.create_index(op.f('ix_control_equipos_licencias_software_software_catalogo_id'), 'licencias_software', ['software_catalogo_id'], unique=False, schema='control_equipos')
    op.create_table('tipos_item_inventario',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('unidad_medida', sa.String(length=50), nullable=False),
    sa.Column('marca', sa.String(length=100), nullable=True),
    sa.Column('modelo', sa.String(length=100), nullable=True),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('codigo_barras', sa.String(length=100), nullable=True),
    sa.Column('modelos_equipo_compatibles', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('proveedor_preferido_id', sa.UUID(), nullable=True),
    sa.Column('stock_minimo', sa.Integer(), nullable=False),
    sa.Column('perecedero', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['proveedor_preferido_id'], ['control_equipos.proveedores.id'], name=op.f('fk_tipos_item_inventario_proveedor_preferido_id_proveedores'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tipos_item_inventario')),
    schema='control_equipos'
    )
    op.create_index(op.f('ix_control_equipos_tipos_item_inventario_categoria'), 'tipos_item_inventario', ['categoria'], unique=False, schema='control_equipos')
    op.create_index(op.f('ix_control_equipos_tipos_item_inventario_codigo_barras'), 'tipos_item_inventario', ['codigo_barras'], unique=True, schema='control_equipos')
    op.create_index(op.f('ix_control_equipos_tipos_item_inventario_marca'), 'tipos_item_inventario', ['marca'], unique=False, schema='control_equipos')
    op.create_index(op.f('ix_control_equipos_tipos_item_inventario_nombre'), 'tipos_item_inventario', ['nombre'], unique=True, schema='control_equipos')
    op.create_index(op.f('ix_control_equipos_tipos_item_inventario_proveedor_preferido_id'), 'tipos_item_inventario', ['proveedor_preferido_id'], unique=False, schema='control_equipos')
    op.create_index(op.f('ix_control_equipos_tipos_item_inventario_sku'), 'tipos_item_inventario', ['sku'], unique=True, schema='control_equipos')
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre_usuario', sa.String(length=100), nullable=False),
    sa.Column('contrasena', sa.String(), nullable=False),
    sa.Column('rol_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('token_temporal', sa.UUID(), nullable=True),
    sa.Column('token_expiracion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('intentos_fallidos', sa.Integer(), nullable=False),
    sa.Column('bloqueado', sa.Boolean(), nullable=False),
    sa.Column('ultimo_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('requiere_cambio_contrasena', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['rol_id'], ['control_equipos.roles.id'], name=op.f('fk_usuarios_rol_id_roles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usuarios')),
    schema='control_equipos'
    )
    op.create_index(op.f('ix_control_equipos_usuarios_email'), 'usuarios', ['email'], unique=True, schema='control_equipos')
    op.create_index(op.f('ix_control_equipos_usuarios_nombre_usuario'), 'usuarios', ['nombre_usuario'], unique=True, schema='control_equipos')
    op.create_index(op.f('ix_control_equipos_usuarios_rol_id'), 'usuarios', ['rol_id'], unique=False, schema='control_equipos')
    op.create_table('asignaciones_licencia',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('licencia_id', sa.UUID(), nullable=False),
    sa.Column('equipo_id', sa.UUID(), nullable=True),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('fecha_asignacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('instalado', sa.Boolean(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.CheckConstraint('NOT (equipo_id IS NOT NULL AND usuario_id IS NOT NULL)', name=op.f('ck_asignaciones_licencia_check_asignacion_exclusiva')),
    sa.CheckConstraint('equipo_id IS NOT NULL OR usuario_id IS NOT NULL', name=op.f('ck_asignaciones_licencia_check_asignacion_target')),
    sa.ForeignKeyConstraint(['equipo_id'], ['control_equipos.equipos.id'], name=op.f('fk_asignaciones_licencia_equipo_id_equipos'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['licencia_id'], ['control_equipos.licencias_software.id'], name=op.f('fk_asignaciones_licencia_licencia_id_licencias_software'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['control_equipos.usuarios.id'], name=op.f('fk_asignaciones_licencia_usuario_id_usuarios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asignaciones_licencia')),
    sa.UniqueConstraint('licencia_id', 'equipo_id', name='uq_asignacion_licencia_equipo'),
    sa.UniqueConstraint('licencia_id', 'usuario_id', name='uq_asignacion_licencia_usuario'),
    schema='control_equipos'
    )
    op.create_index(op.f('ix_control_equipos_asignaciones_licencia_equipo_id'), 'asignaciones_licencia', ['equipo_id'], unique=False, schema='control_equipos')
    op.create_index(op.f('ix_control_equipos_asignaciones_licencia_licencia_id'), 'asignaciones_licencia', ['licencia_id'], unique=False, schema='control_equipos')
    op.create_index(op.f('ix_control_equipos_asignaciones_licencia_usuario_id'), 'asignaciones_licencia', ['usuario_id'], unique=False, schema='control_equipos')
    op.create_table('equipo_componentes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('equipo_padre_id', sa.UUID(), nullable=False),
    sa.Column('equipo_componente_id', sa.UUID(), nullable=False),
    sa.Column('tipo_relacion', sa.String(length=50), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['equipo_componente_id'], ['control_equipos.equipos.id'], name=op.f('fk_equipo_componentes_equipo_componente_id_equipos'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['equipo_padre_id'], ['control_equipos.equipos.id'], name=op.f('fk_equipo_componentes_equipo_padre_id_equipos'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_equipo_componentes')),
    sa.UniqueConstraint('equipo_padre_id', 'equipo_componente_id', 'tipo_relacion', name='uq_componente'),
    schema='control_equipos'
    )
    op.create_index(op.f('ix_control_equipos_equipo_componentes_equipo_componente_id'), 'equipo_componentes', ['equipo_componente_id'], unique=False, schema='control_equipos')
    op.create_index(op.f('ix_control_equipos_equipo_componentes_equipo_padre_id'), 'equipo_componentes', ['equipo_padre_id'], unique=False, schema='control_equipos')
    op.create_table('inventario_stock',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tipo_item_id', sa.UUID(), nullable=False),
    sa.Column('ubicacion', sa.String(length=255), nullable=False),
    sa.Column('lote', sa.String(length=100), nullable=True),
    sa.Column('fecha_caducidad', sa.Date(), nullable=True),
    sa.Column('cantidad_actual', sa.Integer(), nullable=False),
    sa.Column('costo_promedio_ponderado', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('ultima_actualizacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tipo_item_id'], ['control_equipos.tipos_item_inventario.id'], name=op.f('fk_inventario_stock_tipo_item_id_tipos_item_inventario'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventario_stock')),
    sa.UniqueConstraint('tipo_item_id', 'ubicacion', 'lote', name='uq_item_ubicacion_lote'),
    schema='control_equipos'
    )
    op.create_index(op.f('ix_control_equipos_inventario_stock_fecha_caducidad'), 'inventario_stock', ['fecha_caducidad'], unique=False, schema='control_equipos')
    op.create_index(op.f('ix_control_equipos_inventario_stock_lote'), 'inventario_stock', ['lote'], unique=False, schema='control_equipos')
    op.create_index(op.f('ix_control_equipos_inventario_stock_tipo_item_id'), 'inventario_stock', ['tipo_item_id'], unique=False, schema='control_equipos')
    op.create_index(op.f('ix_control_equipos_inventario_stock_ubicacion'), 'inventario_stock', ['ubicacion'], unique=False, schema='control_equipos')
    op.create_table('login_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('nombre_usuario_intento', sa.String(length=100), nullable=True),
    sa.Column('intento', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('exito', sa.Boolean(), nullable=True),
    sa.Column('ip_origen', sa.String(length=100), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('motivo_fallo', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['control_equipos.usuarios.id'], name=op.f('fk_login_logs_usuario_id_usuarios'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_login_logs')),
    schema='control_equipos'
    )
    op.create_index(op.f('ix_control_equipos_login_logs_exito'), 'login_logs', ['exito'], unique=False, schema='control_equipos')
    op.create_index(op.f('ix_control_equipos_login_logs_intento'), 'login_logs', ['intento'], unique=False, schema='control_equipos')
    op.create_index(op.f('ix_control_equipos_login_logs_ip_origen'), 'login_logs', ['ip_origen'], unique=False, schema='control_equipos')
    op.create_index(op.f('ix_control_equipos_login_logs_usuario_id'), 'login_logs', ['usuario_id'], unique=False, schema='control_equipos')
    op.create_table('mantenimiento',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('equipo_id', sa.UUID(), nullable=False),
    sa.Column('tipo_mantenimiento_id', sa.UUID(), nullable=False),
    sa.Column('fecha_programada', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_finalizacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_proximo_mantenimiento', sa.DateTime(timezone=True), nullable=True),
    sa.Column('costo_estimado', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('costo_real', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('tecnico_responsable', sa.Text(), nullable=False),
    sa.Column('proveedor_servicio_id', sa.UUID(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('prioridad', sa.Integer(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('texto_busqueda', postgresql.TSVECTOR(), nullable=True),
    sa.ForeignKeyConstraint(['equipo_id'], ['control_equipos.equipos.id'], name=op.f('fk_mantenimiento_equipo_id_equipos'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proveedor_servicio_id'], ['control_equipos.proveedores.id'], name=op.f('fk_mantenimiento_proveedor_servicio_id_proveedores'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tipo_mantenimiento_id'], ['control_equipos.tipos_mantenimiento.id'], name=op.f('fk_mantenimiento_tipo_mantenimiento_id_tipos_mantenimiento'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mantenimiento')),
    schema='control_equipos'
    )
    op.create_index(op.f('ix_control_equipos_mantenimiento_equipo_id'), 'mantenimiento', ['equipo_id'], unique=False, schema='control_equipos')
    op.create_index(op.f('ix_control_equipos_mantenimiento_estado'), 'mantenimiento', ['estado'], unique=False, schema='control_equipos')
    op.create_index(op.f('ix_control_equipos_mantenimiento_fecha_finalizacion'), 'mantenimiento', ['fecha_finalizacion'], unique=False, schema='control_equipos')
    op.create_index(op.f('ix_control_equipos_mantenimiento_fecha_inicio'), 'mantenimiento', ['fecha_inicio'], unique=False, schema='control_equipos')
    op.create_index(op.f('ix_control_equipos_mantenimiento_fecha_programada'), 'mantenimiento', ['fecha_programada'], unique=False, schema='control_equipos')
    op.create_index(op.f('ix_control_equipos_mantenimiento_fecha_proximo_mantenimiento'), 'mantenimiento', ['fecha_proximo_mantenimiento'], unique=False, schema='control_equipos')
    op.create_index(op.f('ix_control_equipos_mantenimiento_prioridad'), 'mantenimiento', ['prioridad'], unique=False, schema='control_equipos')
    op.create_index(op.f('ix_control_equipos_mantenimiento_proveedor_servicio_id'), 'mantenimiento', ['proveedor_servicio_id'], unique=False, schema='control_equipos')
    op.create_index(op.f('ix_control_equipos_mantenimiento_tipo_mantenimiento_id'), 'mantenimiento', ['tipo_mantenimiento_id'], unique=False, schema='control_equipos')
    op.create_table('movimientos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('equipo_id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('tipo_movimiento', sa.String(length=50), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_prevista_retorno', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_retorno', sa.DateTime(timezone=True), nullable=True),
    sa.Column('origen', sa.Text(), nullable=True),
    sa.Column('destino', sa.Text(), nullable=True),
    sa.Column('proposito', sa.Text(), nullable=True),
    sa.Column('autorizado_por', sa.UUID(), nullable=True),
    sa.Column('recibido_por', sa.Text(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['autorizado_por'], ['control_equipos.usuarios.id'], name=op.f('fk_movimientos_autorizado_por_usuarios'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['equipo_id'], ['control_equipos.equipos.id'], name=op.f('fk_movimientos_equipo_id_equipos'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['control_equipos.usuarios.id'], name=op.f('fk_movimientos_usuario_id_usuarios'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_movimientos')),
    schema='control_equipos'
    )
    op.create_index(op.f('ix_control_equipos_movimientos_autorizado_por'), 'movimientos', ['autorizado_por'], unique=False, schema='control_equipos')
    op.create_index(op.f('ix_control_equipos_movimientos_equipo_id'), 'movimientos', ['equipo_id'], unique=False, schema='control_equipos')
    op.create_index(op.f('ix_control_equipos_movimientos_estado'), 'movimientos', ['estado'], unique=False, schema='control_equipos')
    op.create_index(op.f('ix_control_equipos_movimientos_fecha_hora'), 'movimientos', ['fecha_hora'], unique=False, schema='control_equipos')
    op.create_index(op.f('ix_control_equipos_movimientos_tipo_movimiento'), 'movimientos', ['tipo_movimiento'], unique=False, schema='control_equipos')
    op.create_index(op.f('ix_control_equipos_movimientos_usuario_id'), 'movimientos', ['usuario_id'], unique=False, schema='control_equipos')
    op.create_table('notificaciones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('leido', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_leido', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('urgencia', sa.Integer(), nullable=False),
    sa.Column('referencia_id', sa.UUID(), nullable=True),
    sa.Column('referencia_tabla', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['control_equipos.usuarios.id'], name=op.f('fk_notificaciones_usuario_id_usuarios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notificaciones')),
    schema='control_equipos'
    )
    op.create_index(op.f('ix_control_equipos_notificaciones_created_at'), 'notificaciones', ['created_at'], unique=False, schema='control_equipos')
    op.create_index(op.f('ix_control_equipos_notificaciones_leido'), 'notificaciones', ['leido'], unique=False, schema='control_equipos')
    op.create_index(op.f('ix_control_equipos_notificaciones_referencia_id'), 'notificaciones', ['referencia_id'], unique=False, schema='control_equipos')
    op.create_index(op.f('ix_control_equipos_notificaciones_tipo'), 'notificaciones', ['tipo'], unique=False, schema='control_equipos')
    op.create_index(op.f('ix_control_equipos_notificaciones_urgencia'), 'notificaciones', ['urgencia'], unique=False, schema='control_equipos')
    op.create_index(op.f('ix_control_equipos_notificaciones_usuario_id'), 'notificaciones', ['usuario_id'], unique=False, schema='control_equipos')
    op.create_table('reservas_equipo',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('equipo_id', sa.UUID(), nullable=False),
    sa.Column('usuario_solicitante_id', sa.UUID(), nullable=False),
    sa.Column('fecha_hora_inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_hora_fin', sa.DateTime(timezone=True), nullable=False),
    sa.Column('proposito', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('notas_administrador', sa.Text(), nullable=True),
    sa.Column('notas_devolucion', sa.Text(), nullable=True),
    sa.Column('aprobado_por_id', sa.UUID(), nullable=True),
    sa.Column('fecha_aprobacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('check_in_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('check_out_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['aprobado_por_id'], ['control_equipos.usuarios.id'], name=op.f('fk_reservas_equipo_aprobado_por_id_usuarios'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['equipo_id'], ['control_equipos.equipos.id'], name=op.f('fk_reservas_equipo_equipo_id_equipos'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_solicitante_id'], ['control_equipos.usuarios.id'], name=op.f('fk_reservas_equipo_usuario_solicitante_id_usuarios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reservas_equipo')),
    schema='control_equipos'
    )
    op.create_index(op.f('ix_control_equipos_reservas_equipo_aprobado_por_id'), 'reservas_equipo', ['aprobado_por_id'], unique=False, schema='control_equipos')
    op.create_index(op.f('ix_control_equipos_reservas_equipo_equipo_id'), 'reservas_equipo', ['equipo_id'], unique=False, schema='control_equipos')
    op.create_index(op.f('ix_control_equipos_reservas_equipo_estado'), 'reservas_equipo', ['estado'], unique=False, schema='control_equipos')
    op.create_index(op.f('ix_control_equipos_reservas_equipo_fecha_hora_fin'), 'reservas_equipo', ['fecha_hora_fin'], unique=False, schema='control_equipos')
    op.create_index(op.f('ix_control_equipos_reservas_equipo_fecha_hora_inicio'), 'reservas_equipo', ['fecha_hora_inicio'], unique=False, schema='control_equipos')
    op.create_index(op.f('ix_control_equipos_reservas_equipo_usuario_solicitante_id'), 'reservas_equipo', ['usuario_solicitante_id'], unique=False, schema='control_equipos')
    op.create_table('roles_permisos',
    sa.Column('rol_id', sa.UUID(), nullable=False),
    sa.Column('permiso_id', sa.UUID(), nullable=False),
    sa.Column('otorgado_por', sa.UUID(), nullable=True),
    sa.Column('fecha_otorgamiento', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['otorgado_por'], ['control_equipos.usuarios.id'], name=op.f('fk_roles_permisos_otorgado_por_usuarios'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['permiso_id'], ['control_equipos.permisos.id'], name=op.f('fk_roles_permisos_permiso_id_permisos'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rol_id'], ['control_equipos.roles.id'], name=op.f('fk_roles_permisos_rol_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rol_id', 'permiso_id', name='pk_roles_permisos'),
    schema='control_equipos'
    )
    op.create_table('documentacion',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('equipo_id', sa.UUID(), nullable=True),
    sa.Column('mantenimiento_id', sa.UUID(), nullable=True),
    sa.Column('licencia_id', sa.UUID(), nullable=True),
    sa.Column('tipo_documento_id', sa.UUID(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('enlace', sa.Text(), nullable=False),
    sa.Column('nombre_archivo', sa.String(length=512), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('tamano_bytes', sa.BigInteger(), nullable=True),
    sa.Column('fecha_subida', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('subido_por', sa.UUID(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('verificado_por', sa.UUID(), nullable=True),
    sa.Column('fecha_verificacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notas_verificacion', sa.Text(), nullable=True),
    sa.Column('texto_busqueda', postgresql.TSVECTOR(), server_default=sa.text("''"), nullable=True),
    sa.ForeignKeyConstraint(['equipo_id'], ['control_equipos.equipos.id'], name=op.f('fk_documentacion_equipo_id_equipos'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['licencia_id'], ['control_equipos.licencias_software.id'], name=op.f('fk_documentacion_licencia_id_licencias_software'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['mantenimiento_id'], ['control_equipos.mantenimiento.id'], name=op.f('fk_documentacion_mantenimiento_id_mantenimiento'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subido_por'], ['control_equipos.usuarios.id'], name=op.f('fk_documentacion_subido_por_usuarios'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tipo_documento_id'], ['control_equipos.tipos_documento.id'], name=op.f('fk_documentacion_tipo_documento_id_tipos_documento'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['verificado_por'], ['control_equipos.usuarios.id'], name=op.f('fk_documentacion_verificado_por_usuarios'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documentacion')),
    schema='control_equipos'
    )
    op.create_index(op.f('ix_control_equipos_documentacion_equipo_id'), 'documentacion', ['equipo_id'], unique=False, schema='control_equipos')
    op.create_index(op.f('ix_control_equipos_documentacion_estado'), 'documentacion', ['estado'], unique=False, schema='control_equipos')
    op.create_index(op.f('ix_control_equipos_documentacion_licencia_id'), 'documentacion', ['licencia_id'], unique=False, schema='control_equipos')
    op.create_index(op.f('ix_control_equipos_documentacion_mantenimiento_id'), 'documentacion', ['mantenimiento_id'], unique=False, schema='control_equipos')
    op.create_index(op.f('ix_control_equipos_documentacion_subido_por'), 'documentacion', ['subido_por'], unique=False, schema='control_equipos')
    op.create_index(op.f('ix_control_equipos_documentacion_tipo_documento_id'), 'documentacion', ['tipo_documento_id'], unique=False, schema='control_equipos')
    op.create_index(op.f('ix_control_equipos_documentacion_verificado_por'), 'documentacion', ['verificado_por'], unique=False, schema='control_equipos')
    op.create_index('ix_documentacion_texto_busqueda', 'documentacion', ['texto_busqueda'], unique=False, schema='control_equipos', postgresql_using='gin')
    op.create_table('inventario_movimientos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tipo_item_id', sa.UUID(), nullable=False),
    sa.Column('tipo_movimiento', sa.String(length=50), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('ubicacion_origen', sa.String(length=255), nullable=True),
    sa.Column('ubicacion_destino', sa.String(length=255), nullable=True),
    sa.Column('lote_origen', sa.String(length=100), nullable=True),
    sa.Column('lote_destino', sa.String(length=100), nullable=True),
    sa.Column('equipo_asociado_id', sa.UUID(), nullable=True),
    sa.Column('mantenimiento_id', sa.UUID(), nullable=True),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('fecha_hora', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('costo_unitario', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('motivo_ajuste', sa.Text(), nullable=True),
    sa.Column('referencia_externa', sa.String(length=255), nullable=True),
    sa.Column('referencia_transferencia', sa.UUID(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['equipo_asociado_id'], ['control_equipos.equipos.id'], name=op.f('fk_inventario_movimientos_equipo_asociado_id_equipos'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['mantenimiento_id'], ['control_equipos.mantenimiento.id'], name=op.f('fk_inventario_movimientos_mantenimiento_id_mantenimiento'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tipo_item_id'], ['control_equipos.tipos_item_inventario.id'], name=op.f('fk_inventario_movimientos_tipo_item_id_tipos_item_inventario'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['usuario_id'], ['control_equipos.usuarios.id'], name=op.f('fk_inventario_movimientos_usuario_id_usuarios'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventario_movimientos')),
    schema='control_equipos'
    )
    op.create_index(op.f('ix_control_equipos_inventario_movimientos_equipo_asociado_id'), 'inventario_movimientos', ['equipo_asociado_id'], unique=False, schema='control_equipos')
    op.create_index(op.f('ix_control_equipos_inventario_movimientos_fecha_hora'), 'inventario_movimientos', ['fecha_hora'], unique=False, schema='control_equipos')
    op.create_index(op.f('ix_control_equipos_inventario_movimientos_lote_destino'), 'inventario_movimientos', ['lote_destino'], unique=False, schema='control_equipos')
    op.create_index(op.f('ix_control_equipos_inventario_movimientos_lote_origen'), 'inventario_movimientos', ['lote_origen'], unique=False, schema='control_equipos')
    op.create_index(op.f('ix_control_equipos_inventario_movimientos_mantenimiento_id'), 'inventario_movimientos', ['mantenimiento_id'], unique=False, schema='control_equipos')
    op.create_index(op.f('ix_control_equipos_inventario_movimientos_referencia_transferencia'), 'inventario_movimientos', ['referencia_transferencia'], unique=False, schema='control_equipos')
    op.create_index(op.f('ix_control_equipos_inventario_movimientos_tipo_item_id'), 'inventario_movimientos', ['tipo_item_id'], unique=False, schema='control_equipos')
    op.create_index(op.f('ix_control_equipos_inventario_movimientos_tipo_movimiento'), 'inventario_movimientos', ['tipo_movimiento'], unique=False, schema='control_equipos')
    op.create_index(op.f('ix_control_equipos_inventario_movimientos_ubicacion_destino'), 'inventario_movimientos', ['ubicacion_destino'], unique=False, schema='control_equipos')
    op.create_index(op.f('ix_control_equipos_inventario_movimientos_ubicacion_origen'), 'inventario_movimientos', ['ubicacion_origen'], unique=False, schema='control_equipos')
    op.create_index(op.f('ix_control_equipos_inventario_movimientos_usuario_id'), 'inventario_movimientos', ['usuario_id'], unique=False, schema='control_equipos')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_control_equipos_inventario_movimientos_usuario_id'), table_name='inventario_movimientos', schema='control_equipos')
    op.drop_index(op.f('ix_control_equipos_inventario_movimientos_ubicacion_origen'), table_name='inventario_movimientos', schema='control_equipos')
    op.drop_index(op.f('ix_control_equipos_inventario_movimientos_ubicacion_destino'), table_name='inventario_movimientos', schema='control_equipos')
    op.drop_index(op.f('ix_control_equipos_inventario_movimientos_tipo_movimiento'), table_name='inventario_movimientos', schema='control_equipos')
    op.drop_index(op.f('ix_control_equipos_inventario_movimientos_tipo_item_id'), table_name='inventario_movimientos', schema='control_equipos')
    op.drop_index(op.f('ix_control_equipos_inventario_movimientos_referencia_transferencia'), table_name='inventario_movimientos', schema='control_equipos')
    op.drop_index(op.f('ix_control_equipos_inventario_movimientos_mantenimiento_id'), table_name='inventario_movimientos', schema='control_equipos')
    op.drop_index(op.f('ix_control_equipos_inventario_movimientos_lote_origen'), table_name='inventario_movimientos', schema='control_equipos')
    op.drop_index(op.f('ix_control_equipos_inventario_movimientos_lote_destino'), table_name='inventario_movimientos', schema='control_equipos')
    op.drop_index(op.f('ix_control_equipos_inventario_movimientos_fecha_hora'), table_name='inventario_movimientos', schema='control_equipos')
    op.drop_index(op.f('ix_control_equipos_inventario_movimientos_equipo_asociado_id'), table_name='inventario_movimientos', schema='control_equipos')
    op.drop_table('inventario_movimientos', schema='control_equipos')
    op.drop_index('ix_documentacion_texto_busqueda', table_name='documentacion', schema='control_equipos', postgresql_using='gin')
    op.drop_index(op.f('ix_control_equipos_documentacion_verificado_por'), table_name='documentacion', schema='control_equipos')
    op.drop_index(op.f('ix_control_equipos_documentacion_tipo_documento_id'), table_name='documentacion', schema='control_equipos')
    op.drop_index(op.f('ix_control_equipos_documentacion_subido_por'), table_name='documentacion', schema='control_equipos')
    op.drop_index(op.f('ix_control_equipos_documentacion_mantenimiento_id'), table_name='documentacion', schema='control_equipos')
    op.drop_index(op.f('ix_control_equipos_documentacion_licencia_id'), table_name='documentacion', schema='control_equipos')
    op.drop_index(op.f('ix_control_equipos_documentacion_estado'), table_name='documentacion', schema='control_equipos')
    op.drop_index(op.f('ix_control_equipos_documentacion_equipo_id'), table_name='documentacion', schema='control_equipos')
    op.drop_table('documentacion', schema='control_equipos')
    op.drop_table('roles_permisos', schema='control_equipos')
    op.drop_index(op.f('ix_control_equipos_reservas_equipo_usuario_solicitante_id'), table_name='reservas_equipo', schema='control_equipos')
    op.drop_index(op.f('ix_control_equipos_reservas_equipo_fecha_hora_inicio'), table_name='reservas_equipo', schema='control_equipos')
    op.drop_index(op.f('ix_control_equipos_reservas_equipo_fecha_hora_fin'), table_name='reservas_equipo', schema='control_equipos')
    op.drop_index(op.f('ix_control_equipos_reservas_equipo_estado'), table_name='reservas_equipo', schema='control_equipos')
    op.drop_index(op.f('ix_control_equipos_reservas_equipo_equipo_id'), table_name='reservas_equipo', schema='control_equipos')
    op.drop_index(op.f('ix_control_equipos_reservas_equipo_aprobado_por_id'), table_name='reservas_equipo', schema='control_equipos')
    op.drop_table('reservas_equipo', schema='control_equipos')
    op.drop_index(op.f('ix_control_equipos_notificaciones_usuario_id'), table_name='notificaciones', schema='control_equipos')
    op.drop_index(op.f('ix_control_equipos_notificaciones_urgencia'), table_name='notificaciones', schema='control_equipos')
    op.drop_index(op.f('ix_control_equipos_notificaciones_tipo'), table_name='notificaciones', schema='control_equipos')
    op.drop_index(op.f('ix_control_equipos_notificaciones_referencia_id'), table_name='notificaciones', schema='control_equipos')
    op.drop_index(op.f('ix_control_equipos_notificaciones_leido'), table_name='notificaciones', schema='control_equipos')
    op.drop_index(op.f('ix_control_equipos_notificaciones_created_at'), table_name='notificaciones', schema='control_equipos')
    op.drop_table('notificaciones', schema='control_equipos')
    op.drop_index(op.f('ix_control_equipos_movimientos_usuario_id'), table_name='movimientos', schema='control_equipos')
    op.drop_index(op.f('ix_control_equipos_movimientos_tipo_movimiento'), table_name='movimientos', schema='control_equipos')
    op.drop_index(op.f('ix_control_equipos_movimientos_fecha_hora'), table_name='movimientos', schema='control_equipos')
    op.drop_index(op.f('ix_control_equipos_movimientos_estado'), table_name='movimientos', schema='control_equipos')
    op.drop_index(op.f('ix_control_equipos_movimientos_equipo_id'), table_name='movimientos', schema='control_equipos')
    op.drop_index(op.f('ix_control_equipos_movimientos_autorizado_por'), table_name='movimientos', schema='control_equipos')
    op.drop_table('movimientos', schema='control_equipos')
    op.drop_index(op.f('ix_control_equipos_mantenimiento_tipo_mantenimiento_id'), table_name='mantenimiento', schema='control_equipos')
    op.drop_index(op.f('ix_control_equipos_mantenimiento_proveedor_servicio_id'), table_name='mantenimiento', schema='control_equipos')
    op.drop_index(op.f('ix_control_equipos_mantenimiento_prioridad'), table_name='mantenimiento', schema='control_equipos')
    op.drop_index(op.f('ix_control_equipos_mantenimiento_fecha_proximo_mantenimiento'), table_name='mantenimiento', schema='control_equipos')
    op.drop_index(op.f('ix_control_equipos_mantenimiento_fecha_programada'), table_name='mantenimiento', schema='control_equipos')
    op.drop_index(op.f('ix_control_equipos_mantenimiento_fecha_inicio'), table_name='mantenimiento', schema='control_equipos')
    op.drop_index(op.f('ix_control_equipos_mantenimiento_fecha_finalizacion'), table_name='mantenimiento', schema='control_equipos')
    op.drop_index(op.f('ix_control_equipos_mantenimiento_estado'), table_name='mantenimiento', schema='control_equipos')
    op.drop_index(op.f('ix_control_equipos_mantenimiento_equipo_id'), table_name='mantenimiento', schema='control_equipos')
    op.drop_table('mantenimiento', schema='control_equipos')
    op.drop_index(op.f('ix_control_equipos_login_logs_usuario_id'), table_name='login_logs', schema='control_equipos')
    op.drop_index(op.f('ix_control_equipos_login_logs_ip_origen'), table_name='login_logs', schema='control_equipos')
    op.drop_index(op.f('ix_control_equipos_login_logs_intento'), table_name='login_logs', schema='control_equipos')
    op.drop_index(op.f('ix_control_equipos_login_logs_exito'), table_name='login_logs', schema='control_equipos')
    op.drop_table('login_logs', schema='control_equipos')
    op.drop_index(op.f('ix_control_equipos_inventario_stock_ubicacion'), table_name='inventario_stock', schema='control_equipos')
    op.drop_index(op.f('ix_control_equipos_inventario_stock_tipo_item_id'), table_name='inventario_stock', schema='control_equipos')
    op.drop_index(op.f('ix_control_equipos_inventario_stock_lote'), table_name='inventario_stock', schema='control_equipos')
    op.drop_index(op.f('ix_control_equipos_inventario_stock_fecha_caducidad'), table_name='inventario_stock', schema='control_equipos')
    op.drop_table('inventario_stock', schema='control_equipos')
    op.drop_index(op.f('ix_control_equipos_equipo_componentes_equipo_padre_id'), table_name='equipo_componentes', schema='control_equipos')
    op.drop_index(op.f('ix_control_equipos_equipo_componentes_equipo_componente_id'), table_name='equipo_componentes', schema='control_equipos')
    op.drop_table('equipo_componentes', schema='control_equipos')
    op.drop_index(op.f('ix_control_equipos_asignaciones_licencia_usuario_id'), table_name='asignaciones_licencia', schema='control_equipos')
    op.drop_index(op.f('ix_control_equipos_asignaciones_licencia_licencia_id'), table_name='asignaciones_licencia', schema='control_equipos')
    op.drop_index(op.f('ix_control_equipos_asignaciones_licencia_equipo_id'), table_name='asignaciones_licencia', schema='control_equipos')
    op.drop_table('asignaciones_licencia', schema='control_equipos')
    op.drop_index(op.f('ix_control_equipos_usuarios_rol_id'), table_name='usuarios', schema='control_equipos')
    op.drop_index(op.f('ix_control_equipos_usuarios_nombre_usuario'), table_name='usuarios', schema='control_equipos')
    op.drop_index(op.f('ix_control_equipos_usuarios_email'), table_name='usuarios', schema='control_equipos')
    op.drop_table('usuarios', schema='control_equipos')
    op.drop_index(op.f('ix_control_equipos_tipos_item_inventario_sku'), table_name='tipos_item_inventario', schema='control_equipos')
    op.drop_index(op.f('ix_control_equipos_tipos_item_inventario_proveedor_preferido_id'), table_name='tipos_item_inventario', schema='control_equipos')
    op.drop_index(op.f('ix_control_equipos_tipos_item_inventario_nombre'), table_name='tipos_item_inventario', schema='control_equipos')
    op.drop_index(op.f('ix_control_equipos_tipos_item_inventario_marca'), table_name='tipos_item_inventario', schema='control_equipos')
    op.drop_index(op.f('ix_control_equipos_tipos_item_inventario_codigo_barras'), table_name='tipos_item_inventario', schema='control_equipos')
    op.drop_index(op.f('ix_control_equipos_tipos_item_inventario_categoria'), table_name='tipos_item_inventario', schema='control_equipos')
    op.drop_table('tipos_item_inventario', schema='control_equipos')
    op.drop_index(op.f('ix_control_equipos_licencias_software_software_catalogo_id'), table_name='licencias_software', schema='control_equipos')
    op.drop_index(op.f('ix_control_equipos_licencias_software_proveedor_id'), table_name='licencias_software', schema='control_equipos')
    op.drop_index(op.f('ix_control_equipos_licencias_software_fecha_expiracion'), table_name='licencias_software', schema='control_equipos')
    op.drop_index(op.f('ix_control_equipos_licencias_software_clave_producto'), table_name='licencias_software', schema='control_equipos')
    op.drop_table('licencias_software', schema='control_equipos')
    op.drop_index(op.f('ix_control_equipos_equipos_proveedor_id'), table_name='equipos', schema='control_equipos')
    op.drop_index(op.f('ix_control_equipos_equipos_numero_serie'), table_name='equipos', schema='control_equipos')
    op.drop_index(op.f('ix_control_equipos_equipos_nombre'), table_name='equipos', schema='control_equipos')
    op.drop_index(op.f('ix_control_equipos_equipos_modelo'), table_name='equipos', schema='control_equipos')
    op.drop_index(op.f('ix_control_equipos_equipos_marca'), table_name='equipos', schema='control_equipos')
    op.drop_index(op.f('ix_control_equipos_equipos_estado_id'), table_name='equipos', schema='control_equipos')
    op.drop_index(op.f('ix_control_equipos_equipos_codigo_interno'), table_name='equipos', schema='control_equipos')
    op.drop_index(op.f('ix_control_equipos_equipos_centro_costo'), table_name='equipos', schema='control_equipos')
    op.drop_table('equipos', schema='control_equipos')
    op.drop_index(op.f('ix_control_equipos_tipos_mantenimiento_nombre'), table_name='tipos_mantenimiento', schema='control_equipos')
    op.drop_table('tipos_mantenimiento', schema='control_equipos')
    op.drop_index(op.f('ix_control_equipos_tipos_documento_nombre'), table_name='tipos_documento', schema='control_equipos')
    op.drop_table('tipos_documento', schema='control_equipos')
    op.drop_index(op.f('ix_control_equipos_software_catalogo_nombre'), table_name='software_catalogo', schema='control_equipos')
    op.drop_index(op.f('ix_control_equipos_software_catalogo_fabricante'), table_name='software_catalogo', schema='control_equipos')
    op.drop_index(op.f('ix_control_equipos_software_catalogo_categoria'), table_name='software_catalogo', schema='control_equipos')
    op.drop_table('software_catalogo', schema='control_equipos')
    op.drop_index(op.f('ix_control_equipos_roles_nombre'), table_name='roles', schema='control_equipos')
    op.drop_table('roles', schema='control_equipos')
    op.drop_index(op.f('ix_control_equipos_proveedores_rnc'), table_name='proveedores', schema='control_equipos')
    op.drop_index(op.f('ix_control_equipos_proveedores_nombre'), table_name='proveedores', schema='control_equipos')
    op.drop_table('proveedores', schema='control_equipos')
    op.drop_index(op.f('ix_control_equipos_permisos_nombre'), table_name='permisos', schema='control_equipos')
    op.drop_table('permisos', schema='control_equipos')
    op.drop_index(op.f('ix_control_equipos_estados_equipo_nombre'), table_name='estados_equipo', schema='control_equipos')
    op.drop_table('estados_equipo', schema='control_equipos')
    op.drop_table('backup_logs', schema='control_equipos')
    op.drop_table('audit_log', schema='control_equipos')
    # ### end Alembic commands ###
    